import type { LucideIcon } from "lucide-react"
import {
  Wrench,
  Laptop,
  Monitor,
  Cpu,
  HardDrive,
  MemoryStick,
  Server,
  Printer,
  Keyboard,
  Mouse,
  Smartphone,
  Tablet,
  Usb,
  CircuitBoard,
  Database,
  Cloud,
  CloudUpload,
  Download,
  Upload,
  RefreshCw,
  Save,
  Folder,
  FileCode,
  Code,
  Terminal,
  Settings,
  Cog,
  Wifi,
  Router,
  Network,
  Globe,
  Shield,
  ShieldCheck,
  Lock,
  Bug,
  Scan,
  KeyRound,
  Fingerprint,
  Headphones,
  Webcam,
  Battery,
  BatteryCharging,
  Plug,
  Zap,
  Sparkles,
  Rocket,
  TrendingUp,
  BarChart3,
  LineChart,
  Users,
  UserCog,
  Phone,
  Mail,
  MessageSquare,
  LifeBuoy,
  HelpCircle,
  Clock,
  Calendar,
  MapPin,
  Truck,
  Package,
  ShoppingCart,
  CreditCard,
  Award,
  Star,
  CheckCircle2,
  AlertTriangle,
  Hammer,
  Layers,
  Boxes,
  HardHat,
} from "lucide-react"
export type InformaticaIconSlug = keyof typeof INFORMATICA_ICON_MAP

export type InformaticaIconGroup = {
  id: string
  label: string
  icons: { slug: InformaticaIconSlug; label: string }[]
}

export const INFORMATICA_ICON_MAP = {
  wrench: Wrench,
  hammer: Hammer,
  laptop: Laptop,
  monitor: Monitor,
  cpu: Cpu,
  "hard-drive": HardDrive,
  "memory-stick": MemoryStick,
  server: Server,
  printer: Printer,
  keyboard: Keyboard,
  mouse: Mouse,
  smartphone: Smartphone,
  tablet: Tablet,
  usb: Usb,
  "circuit-board": CircuitBoard,
  database: Database,
  cloud: Cloud,
  "cloud-upload": CloudUpload,
  download: Download,
  upload: Upload,
  "refresh-cw": RefreshCw,
  save: Save,
  folder: Folder,
  "file-code": FileCode,
  code: Code,
  terminal: Terminal,
  settings: Settings,
  cog: Cog,
  wifi: Wifi,
  router: Router,
  network: Network,
  globe: Globe,
  shield: Shield,
  "shield-check": ShieldCheck,
  lock: Lock,
  bug: Bug,
  scan: Scan,
  "key-round": KeyRound,
  fingerprint: Fingerprint,
  headphones: Headphones,
  webcam: Webcam,
  battery: Battery,
  "battery-charging": BatteryCharging,
  plug: Plug,
  zap: Zap,
  sparkles: Sparkles,
  rocket: Rocket,
  "trending-up": TrendingUp,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  users: Users,
  "user-cog": UserCog,
  phone: Phone,
  mail: Mail,
  "message-square": MessageSquare,
  "life-buoy": LifeBuoy,
  "help-circle": HelpCircle,
  clock: Clock,
  calendar: Calendar,
  "map-pin": MapPin,
  truck: Truck,
  package: Package,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  award: Award,
  star: Star,
  "check-circle": CheckCircle2,
  "alert-triangle": AlertTriangle,
  layers: Layers,
  boxes: Boxes,
  "hard-hat": HardHat,
} as const satisfies Record<string, LucideIcon>

export const INFORMATICA_ICON_GROUPS: InformaticaIconGroup[] = [
  {
    id: "hardware",
    label: "Hardware",
    icons: [
      { slug: "laptop", label: "Notebook" },
      { slug: "monitor", label: "Monitor" },
      { slug: "cpu", label: "Processador" },
      { slug: "hard-drive", label: "HD / SSD" },
      { slug: "memory-stick", label: "Memória RAM" },
      { slug: "server", label: "Servidor" },
      { slug: "printer", label: "Impressora" },
      { slug: "keyboard", label: "Teclado" },
      { slug: "mouse", label: "Mouse" },
      { slug: "smartphone", label: "Celular" },
      { slug: "tablet", label: "Tablet" },
      { slug: "usb", label: "USB / periféricos" },
      { slug: "circuit-board", label: "Placa / componentes" },
      { slug: "battery", label: "Bateria" },
      { slug: "battery-charging", label: "Carregamento" },
      { slug: "plug", label: "Energia / cabos" },
    ],
  },
  {
    id: "rede",
    label: "Rede e internet",
    icons: [
      { slug: "wifi", label: "Wi‑Fi" },
      { slug: "router", label: "Roteador" },
      { slug: "network", label: "Rede" },
      { slug: "globe", label: "Internet" },
      { slug: "cloud", label: "Nuvem" },
      { slug: "cloud-upload", label: "Backup na nuvem" },
    ],
  },
  {
    id: "software",
    label: "Software e dados",
    icons: [
      { slug: "download", label: "Instalação" },
      { slug: "upload", label: "Envio de arquivos" },
      { slug: "refresh-cw", label: "Formatação / reset" },
      { slug: "save", label: "Backup" },
      { slug: "database", label: "Banco de dados" },
      { slug: "folder", label: "Arquivos" },
      { slug: "file-code", label: "Desenvolvimento" },
      { slug: "code", label: "Código" },
      { slug: "terminal", label: "Terminal" },
      { slug: "settings", label: "Configuração" },
      { slug: "cog", label: "Ajustes finos" },
    ],
  },
  {
    id: "seguranca",
    label: "Segurança",
    icons: [
      { slug: "shield", label: "Proteção" },
      { slug: "shield-check", label: "Seguro / verificado" },
      { slug: "lock", label: "Bloqueio / senha" },
      { slug: "bug", label: "Vírus / malware" },
      { slug: "scan", label: "Varredura" },
      { slug: "key-round", label: "Chave / acesso" },
      { slug: "fingerprint", label: "Biometria" },
      { slug: "alert-triangle", label: "Alerta" },
    ],
  },
  {
    id: "suporte",
    label: "Suporte e atendimento",
    icons: [
      { slug: "wrench", label: "Manutenção" },
      { slug: "hammer", label: "Reparo" },
      { slug: "hard-hat", label: "Instalação técnica" },
      { slug: "headphones", label: "Suporte" },
      { slug: "life-buoy", label: "Ajuda remota" },
      { slug: "message-square", label: "Chat / mensagem" },
      { slug: "phone", label: "Telefone" },
      { slug: "mail", label: "E-mail" },
      { slug: "help-circle", label: "Dúvidas" },
      { slug: "clock", label: "Agendamento" },
      { slug: "calendar", label: "Visita técnica" },
      { slug: "map-pin", label: "Atendimento local" },
      { slug: "truck", label: "Coleta / entrega" },
    ],
  },
  {
    id: "negocios",
    label: "Negócios e destaque",
    icons: [
      { slug: "trending-up", label: "Crescimento" },
      { slug: "bar-chart", label: "Relatórios" },
      { slug: "line-chart", label: "Métricas" },
      { slug: "users", label: "Equipe / clientes" },
      { slug: "user-cog", label: "Gestão" },
      { slug: "shopping-cart", label: "Vendas" },
      { slug: "credit-card", label: "Pagamento" },
      { slug: "package", label: "Pacote / combo" },
      { slug: "award", label: "Qualidade" },
      { slug: "star", label: "Destaque" },
      { slug: "sparkles", label: "Premium" },
      { slug: "rocket", label: "Performance" },
      { slug: "zap", label: "Rápido" },
      { slug: "check-circle", label: "Concluído" },
    ],
  },
]

export const ALL_INFORMATICA_ICONS = INFORMATICA_ICON_GROUPS.flatMap((g) => g.icons)

export function getServiceIcon(name: string | null | undefined): LucideIcon {
  if (!name?.trim()) return Wrench
  const slug = name.trim().toLowerCase()
  const mapped = INFORMATICA_ICON_MAP[slug as InformaticaIconSlug]
  if (mapped) return mapped
  return Wrench
}
